name       : media-player-info
version    : '23'
release    : 2
source     :
    - https://www.freedesktop.org/software/media-player-info/media-player-info-23.tar.gz : a9ab6de0b497f6e13efc2cbe45a4fe06982145d786674c24274c3ed909ecc8cb
license    : BSD-3-Clause
component  : multimedia.library
summary    : Media Player Capability Library
description: |
    media-player-info is a repository of data files describing media player (only USB Mass Storage ones) capabilities. These files contain information about the directory layout to use to add music to these devices, about the supported file formats.
setup      : |
    %configure
build      : |
    %make
install    : |
    %make_install
