name       : media-player-info
version    : 22
release    : 1
source     :
    - https://www.freedesktop.org/software/media-player-info/media-player-info-22.tar.gz : 7ee7d7712834860533c46b16947238ef5b5d72f394fa7fb52783a15fba7b2336
license    : BSD-3-Clause
component  : multimedia.library
summary    : Media Player Capability Library
description: |
    media-player-info is a repository of data files describing media player (only USB Mass Storage ones) capabilities. These files contain information about the directory layout to use to add music to these devices, about the supported file formats.
setup      : |
    %configure
build      : |
    %make
install    : |
    %make_install
